server:
  port: 8001
  servlet:
    context-path: /
spring:
  application:
    name: rabbit-producer
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  rabbitmq:
    host: 121.5.129.238
    port: 5672
    username: guest
    password: myqqmimaishjk123
    # 使用启用消息确认模式
    publisher-confirms: true

    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual


  mail:
    host: smtp.163.com
    username: [username]
    password: [password]
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true
          required: true
